# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Install Docker client
          command: apk add docker-cli
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t trispad/circleci-test:$TAG .
          echo "${DOCKER_PASS}" | docker login --username "${DOCKER_USER}" --password-stdin
          docker push trispad/circleci-test:$TAG
  test:
    docker:
      - image: trispad/circleci-test:0.1.$CIRCLE_BUILD_NUM
        auth:
          username: ${DOCKER_USER}
          password: ${DOCKER_PASS}
    steps:
      - checkout
      - run: ls *
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires: 
            - build

# Use a package of configuration called an orb.
#orbs:
  # Declare a dependency on the welcome-orb
#  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
#workflows:
  # Name the workflow "welcome"
#  welcome:
    # Run the welcome/run job in its own container
#    jobs:
#

#      - welcome/run
